SELECT TOP (1000) [Date]
      ,[Store_ID]
      ,[Product_ID]
      ,[Category]
      ,[Region]
      ,[Inventory_Level]
      ,[Units_Sold]
      ,[Units_Ordered]
      ,[Price]
      ,[Discount]
      ,[Weather_Condition]
      ,[Promotion]
      ,[Competitor_Pricing]
      ,[Seasonality]
      ,[Epidemic]
      ,[Demand]
  FROM [ car sales].[dbo].[sales_data]

  SELECT TOP (1000) [Date]
      ,[Store_ID]
      ,[Product_ID]
      ,[Category]
      ,[Region]
      ,[Inventory_Level]
      ,[Units_Sold]
      ,[Units_Ordered]
      ,[Price]
      ,[Discount]
      ,[Weather_Condition]
      ,[Promotion]
      ,[Competitor_Pricing]
      ,[Seasonality]
      ,[Epidemic]
      ,[Demand]
  FROM [car sales].[dbo].[sales]

USE [ car sales]

SELECT*
FROM sales

SELECT 
  ---CLEANING SALES DATASET
  
  --CHECKING FOR NULLS

SELECT *
  FROM SALES 
  WHERE DATE IS NULL
  OR Store_ID IS NULL
  OR Product_ID	IS NULL
  OR Category IS NULL
  OR Region IS NULL
  OR Inventory_Level IS NULL
  OR Units_Sold	IS NULL
  OR Units_Ordered IS NULL
  OR Price IS NULL
  OR Discount IS NULL
  OR Weather_Condition IS NULL	
  OR Promotion IS NULL
  OR Competitor_Pricing	IS NULL
  OR Seasonality IS NULL
  OR Epidemic IS NULL 
  OR Demand IS NULL ----- EMPTY VALUES NOT FOUND

  --CHECKING FOR DUPLICATE VALUES

SELECT Date,Store_ID,Product_ID,Category,Region,Inventory_Level,Units_Sold,Units_Ordered,Price,Discount,Weather_Condition,Promotion,Competitor_Pricing,Seasonality,Epidemic,Demand
FROM sales
GROUP BY Date, Store_ID,Product_ID,Category,Region,Inventory_Level,Units_Sold,Units_Ordered,Price,Discount,Weather_Condition,Promotion,Competitor_Pricing,Seasonality,Epidemic,Demand
HAVING COUNT(*) > 1  ---NO DUPLICTE FOUND


----CALCULATING REVENUE
---ADDING IT THE TABLE
ALTER TABLE SALES
ADD REVENUE AS ROUND((Units_Sold * PRICE),2 )


---CACULATING  DISCOUNTED REVENUE
SELECT ROUND((Units_Sold * DISCOUNTED_PRICE),2 ) DISCOUNTED_REVENUE
FROM
(
SELECT Units_Sold,Price*1-(DISCOUNT * 1.0 / 100) AS DISCOUNTED_PRICE
 FROM sales 
 ) AS SUB

 --Adding discounted revenue to the table

 ALTER TABLE SALES
 ADD DISCOUNTED_REVENUE AS Units_Sold *(Price * 1-(DISCOUNT * 1.0 / 100)) 

---YEARLY TRENDS
SELECT YEAR(DATE) AS YEAR ,SUM(DISCOUNTED_REVENUE) REVENUE_
FROM sales
GROUP BY YEAR(DATE)
ORDER BY REVENUE_ DESC----2022 HAD MORE SALES


---YEARLY TRENDS %
--THERE WAS A -3% DECREASE IN 2023 (2024 JUST HAS 1 MONTH)
SELECT YEAR,
REVENUE_-PREVIOUSYEAR AS DIFFERENCE,
ROUND(((REVENUE_-PREVIOUSYEAR)/PREVIOUSYEAR)*100,0 )AS PERCENTAGE_GROWTH
FROM
(SELECT YEAR(DATE) AS YEAR ,SUM(DISCOUNTED_REVENUE) REVENUE_,NULLIF(LAG(SUM(DISCOUNTED_REVENUE)) OVER (ORDER BY YEAR(DATE)),0) AS PREVIOUSYEAR
FROM sales
GROUP BY YEAR(DATE)
)AS SALE

----MONTHLY TRENDS

SELECT YEAR(DATE) AS YEAR ,MONTH(DATE) AS MONTH_ ,SUM(DISCOUNTED_REVENUE) REVENUE_
FROM sales
GROUP BY YEAR(DATE),MONTH(DATE)
ORDER BY YEAR(DATE) ,REVENUE_ DESC,MONTH(DATE)DESC

---QUATERLY TRENDS
SELECT YEAR(DATE) AS YEAR ,DATEPART(QUARTER,DATE) AS QUATERS_ ,SUM(DISCOUNTED_REVENUE) REVENUE_
FROM sales
GROUP BY YEAR(DATE),DATEPART(QUARTER,DATE)
ORDER BY YEAR(DATE) ,REVENUE_ DESC,DATEPART(QUARTER,DATE)

---DAILY TRENDS
SELECT  DATEname(WEEKDAY,DATE) AS DAYS_ ,SUM(DISCOUNTED_REVENUE) REVENUE_
FROM sales
GROUP BY DATENAME(WEEKDAY,DATE)
ORDER BY REVENUE_ DESC,DATENAME(WEEKDAY,DATE)


-----TOP SELLING PRODUCT PER DAY
SELECT DAYS_,CATEGORY,RANK
FROM
(
SELECT DAYS_ ,CATEGORY,REVENUE_,
RANK() OVER (PARTITION BY DAYS_ ORDER BY REVENUE_ DESC ) AS RANK
FROM
(SELECT  DATENAME(WEEKDAY,DATE) AS DAYS_ ,SUM(DISCOUNTED_REVENUE) REVENUE_,Category
FROM sales
GROUP BY DATENAME(WEEKDAY,DATE),Category
)AS ATE
)AS SUB
WHERE RANK =1
ORDER BY DAYS_ DESC ,RANK 



---TOP SELLING PRODUCT CATEGORY
SELECT CATEGORY,SUM(DISCOUNTED_REVENUE) REVENUE_
FROM SALES
GROUP BY CATEGORY
ORDER BY SUM(DISCOUNTED_REVENUE) DESC

---TOP SELLING PRODUCT CATEGORY FOR 5 STORES
SELECT Store_ID, CATEGORY,SUM(DISCOUNTED_REVENUE) AS REVENUE_PER_STORE
FROM SALES
GROUP BY CATEGORY,Store_ID
ORDER BY Store_ID DESC,SUM(DISCOUNTED_REVENUE)DESC-----ONLY STORE 4 HAS MORE FURNITURE AND CLOTHING SALES THAN GROCERIES

---REGION WITH HIGHEST SALES

SELECT REGION,SUM(DISCOUNTED_REVENUE) AS REVENUE_,SUM(Units_Ordered) AS ORDERS
FROM SALES
GROUP BY REGION 
ORDER BY REVENUE_ DESC,ORDERS DESC

--STORES WITH HIGHEST REVENUE
SELECT STORE_ID ,SUM(DISCOUNTED_REVENUE) AS REVENUE_
FROM sales
GROUP BY STORE_ID 
ORDER BY REVENUE_ DESC

 --MOST PRICED CATEGORY
   SELECT AVG(PRICE)_PRICE,CATEGORY
   FROM SALES
   GROUP BY Category
   ORDER BY  AVG(PRICE) DESC


---QTY DECREASE OR INCREASE WITH PRICE
SELECT CATEGORY,AVG(PRICE),SUM(Units_Sold) TOTALSALES
FROM SALES 
GROUP BY CategorY
ORDER BY SUM(Units_Sold) DESC



--SEASONALITY TREND: MOST SOLD PRODUCT EACH SEASON
SELECT YEAR,CATEGORY,Weather_Condition,RANK
FROM
(
SELECT YEAR,Weather_Condition,CATEGORY,
RANK()OVER (PARTITION BY YEAR,Weather_Condition ORDER BY Revenue_ DESC) AS RANK
FROM
(SELECT 
  YEAR(DATE) AS YEAR,
  Weather_Condition,CATEGORY,
  SUM(DISCOUNTED_REVENUE) AS Revenue_
FROM 
  sales
GROUP BY 
  YEAR(DATE), Weather_Condition,Category
  )AS VV
  )AS YYY
  WHERE RANK =1
ORDER BY 
  YEAR DESC,
  Weather_Condition
 
 ----SEASONS WITH MOST SALES
SELECT SUM(DISCOUNTED_REVENUE) REVENUE_,Weather_Condition
FROM sales
GROUP BY Weather_Condition
ORDER BY REVENUE_ DESC

 
----PANDEMIC

SELECT YEAR(DATE) YEAR ,SUM(DISCOUNTED_REVENUE)_REVENUE
FROM sales
WHERE EPIDEMIC =1
GROUP BY YEAR(DATE)

SELECT YEAR(DATE) YEAR ,SUM(DISCOUNTED_REVENUE)_REVENUE
FROM sales
WHERE EPIDEMIC =0
GROUP BY YEAR(DATE)

----THERE WAS A 85% DECREASE IN SALES DURING EPIDEMIC PERIOD
SELECT
 ((EPIDEMICSALES -NO_EPIDEMICSALES)/NO_EPIDEMICSALES)*100
 FROM
(SELECT SUM(CASE WHEN EPIDEMIC =0 THEN DISCOUNTED_REVENUE ELSE 0 END) AS NO_EPIDEMICSALES,
SUM(CASE WHEN EPIDEMIC =1 THEN DISCOUNTED_REVENUE ELSE 0 END) AS EPIDEMICSALES
FROM sales
) AS D


---DISCOUNT AND PROMOTIONS

ALTER TABLE SALES
  ADD DISCOUNT_GROUP AS CASE 
    WHEN Discount = 0 THEN '0% DISCOUNT'
    WHEN Discount =5 THEN '5% DISCOUNT'
    WHEN Discount =10 THEN '10% DISCOUNT'
    WHEN Discount =15 THEN '15% DISCOUNT'
	WHEN Discount =20 THEN '20% DISCOUNT'
	WHEN Discount =25 THEN '25% DISCOUNT'
    ELSE '31% or more DISCOUNT'
  END

  ----MOST SOLD CATEGORY DURING PROMOTION
 SELECT CATEGORY,Promotion, SUM(DISCOUNTED_REVENUE) REVENUE_
  FROM sales
  WHERE PROMOTION = 1
  GROUP BY Promotion,CATEGORY
  ORDER BY REVENUE_ DESC


 --- WHAT DISCOUNT DROVE MOST SALES
  ---DISCOUNT PERCENTAGE WITH MOST SALES = 10% DISCOUNT HAD MORE SALES
SELECT  SUM(DISCOUNTED_REVENUE) REVENUE_ ,DISCOUNT_GROUP
  FROM sales
  WHERE Discount_GROUP != '0% DISCOUNT'
  GROUP BY DISCOUNT_GROUP
  ORDER BY REVENUE_ DESC

  ---ORDERS VS ORDERS SOLD DURING PROMOTION AND NON-PROMITION
 SELECT SUM(UNITS_SOLD) ORDERSSOLD_,SUM(Units_Ordered)ORDERS_,Promotion
 FROM SALES
 GROUP BY Promotion ,Store_ID
 ORDER BY ORDERS_ DESC,Store_ID DESC  ----ORDERS WERE NOT BEEN MEANT DURING THE PROMOTION PRIOD AND THEY WERE OBVIOUSLY MORE ORDERS

 --DID  DISCOUNT DURING PROMOTION DRIVE MORE REVENUE  =NO
--- PROMOTION DIDNT DRIVE MORE REVENUE(COS OF EPIDEMIC)
 SELECT  SUM(DISCOUNTED_REVENUE) REVENUE_ ,DISCOUNT_GROUP,Promotion
  FROM sales
  WHERE Discount_GROUP != '0% DISCOUNT' AND PROMOTION = 1
  GROUP BY DISCOUNT_GROUP,PROMOTION
  ----ORDER BY REVENUE_ DESC
  UNION ALL
SELECT  SUM(DISCOUNTED_REVENUE) REVENUE_ ,DISCOUNT_GROUP,PROMOTION
  FROM sales
  WHERE Discount_GROUP != '0% DISCOUNT' AND PROMOTION = 0
  GROUP BY DISCOUNT_GROUP,PROMOTION
  ORDER BY REVENUE_ DESC
 


--- THERE 40% IN REVENUE DECREASE DURING PROMOTION COMPARED TO NON-PROMOTION
WITH CTE AS (SELECT 
  CASE 
    WHEN Promotion = 1 THEN 'Promotion'
    WHEN Promotion = 0 THEN 'No Promotion'
  END AS Promotion_Type,SUM(Units_Ordered) TOTAL_ORDERS,
  SUM(DISCOUNTED_REVENUE) AS Total_Revenue, Promotion
FROM 
  sales
GROUP BY 
  Promotion
),

 RRR AS (SELECT SUM(CASE WHEN Promotion = 1 THEN Total_Revenue END) AS PROMOTEDGOODS,
    SUM(CASE  WHEN Promotion = 0 THEN Total_Revenue END) AS NONPROMOTEDGOODS
    FROM CTE)

    SELECT (PROMOTEDGOODS-NONPROMOTEDGOODS)/NONPROMOTEDGOODS*100
    FROM RRR


     --- WHY THOUGH (LETS CHECK ) IS IT THE THAT ORDERS WERE LOW OR DELIVERED ORDERS WERE NOT MEANT
    ----THERE WAS 5% INCREASE IN ORDERS DURING PROMOTION
WITH CTES AS (SELECT 
  CASE 
    WHEN Promotion = 1 THEN 'Promotion'
    WHEN Promotion = 0 THEN 'No Promotion'
  END AS Promotion_Type,SUM(Units_Ordered) TOTAL_ORDERS,
   Promotion
FROM 
  sales
GROUP BY 
  Promotion
),
 RRR AS (SELECT SUM(CASE WHEN Promotion = 1 THEN TOTAL_ORDERS END) AS PROMOTEDGOODS,
    SUM(CASE  WHEN Promotion = 0 THEN TOTAL_ORDERS END) AS NONPROMOTEDGOODS
    FROM CTES)

    SELECT (PROMOTEDGOODS-NONPROMOTEDGOODS)/NONPROMOTEDGOODS*100 AS ORDERS
    FROM RRR

    ---IN WHAT MONTHS WERE PROMOTION RUNNING (PROMOTION RAN ALL THROUGH)
 SELECT YEAR(Date),DATENAME(MONTH,Date) AS YEAR_
 FROM sales
 WHERE PROMOTION= 1
 GROUP BY Promotion,YEAR(Date) , DATENAME(MONTH,Date)
 ORDER BY YEAR(Date) 


--INVENTORY LEVEL ANALYSIS
SELECT
CATEGORY,
SUM(Units_Sold)*100/SUM(Inventory_Level) STOCK_UTILIZATION,  --- OVER STOCK
SUM(Units_Sold)/SUM(Units_Ordered) AS FUFILMENT_RATE-- 98% OF ORDERS ARE BEEN MET
FROM sales
GROUP BY Category

---DEMAND 


SELECT CATEGORY,
(CAST(SUM(Units_Sold) AS DECIMAL (10,2))/SUM(DEMAND)) AS DEMAND_EFFICIENCY
FROM sales
GROUP BY Category--- (DEMANDS WERE NOT FULLY MET)

----CATEGORIES WITH HIGHEST DEMAND
SELECT CATEGORY,
SUM(DEMAND)
FROM sales
GROUP BY Category
ORDER BY SUM(DEMAND) DESC


-- Demand_to_Sales_Ratio
SELECT CATEGORY,
SUM(DEMAND)/CAST(SUM(Units_Sold) AS DECIMAL (10,2)) AS Demand_to_Sales_Ratio
FROM sales
GROUP BY Category

---COMPETITORS PRICE VS OUR PRICE
SELECT CATEGORY, 
AVG(PRICE)/AVG(COMPETITOR_PRICING)
FROM SALES
GROUP BY Category ------CHEAPER THAN COMPETITOR PRICE



